In [11]:
# suppose you have unstructured texts and you have to clean text then 
# you have to classiy each text into a specific sentiment(positive, Negative ).
# Then you have t create a dataframe in which you will manage 
# first column as text second column as sentiment .

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv(r"C:\codings\datasets\noisy_text_dataset_100_rows.csv")

In [14]:
df

                                                 text
0   Check out https://www.amazon.com for great dea...
1   <html><body><h1>Welcome</h1></body></html> Row...
2   Wow!!! This product is AMAZING!!! :) Row-3 !!!...
3   Visit our website at http://example.org/contac...
4   <div class='review'>Best purchase ever!!!</div...
..                                                ...
95  I can't believe this worked... unbelievable!!!...
96  Email me at test@example.com!!! Row-97 !!! <br...
97  <p>Error 404: Page not found!!!</p> Row-98 !!!...
98  Special offer >>> https://shop.example.com/dea...
99  The movie was great!!! #awesome #fun Row-100 !...

[100 rows x 1 columns]

In [15]:
!pip install textblob

Requirement already satisfied: textblob in C:\Users\asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in C:\Users\asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from textblob) (3.9.2)
Requirement already satisfied: click in C:\Users\asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk>=3.9->textblob) (8.3.1)
Requirement already satisfied: joblib in C:\Users\asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk>=3.9->textblob) (2026.1.15)
Requirement already satisfied: tqdm in C:\Users\asus\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in C:\Users\asus\AppData\Roaming\Python\Python313\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import string
string.punctuation
from textblob import TextBlob

In [17]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'' , text)


def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern. sub(r'' , text)


exclude = string.punctuation

def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [18]:
df['text' ] = df['text'].apply(remove_punc)
df['text' ] = df['text'].apply(remove_url)
df['text' ] = df['text'].apply(remove_html_tags)

In [19]:
df

                                                 text
0   Check out httpswwwamazoncom for great deals Ro...
1   htmlbodyh1Welcomeh1bodyhtml Row2  br httpstest...
2   Wow This product is AMAZING  Row3  br httpstes...
3   Visit our website at httpexampleorgcontactuser...
4   div classreviewBest purchase everdiv Row5  br ...
..                                                ...
95  I cant believe this worked unbelievable Row96 ...
96  Email me at testexamplecom Row97  br httpstest...
97  pError 404 Page not foundp Row98  br httpstest...
98  Special offer  httpsshopexamplecomdeals  Row99...
99  The movie was great awesome fun Row100  br htt...

[100 rows x 1 columns]

In [20]:
def textblob_sentiment_analysis(review):
    sentiment = TextBlob(review).sentiment
    if sentiment.polarity > 0.1 :
        return 'Positive'
    elif sentiment.polarity < -0.1 :
        return 'Negative'
    else:
        return 'Neutral'

In [22]:
df['Sentiment'] = df['text'].apply(textblob_sentiment_analysis)

In [23]:
df

                                                 text Sentiment
0   Check out httpswwwamazoncom for great deals Ro...  Positive
1   htmlbodyh1Welcomeh1bodyhtml Row2  br httpstest...   Neutral
2   Wow This product is AMAZING  Row3  br httpstes...  Positive
3   Visit our website at httpexampleorgcontactuser...   Neutral
4   div classreviewBest purchase everdiv Row5  br ...   Neutral
..                                                ...       ...
95  I cant believe this worked unbelievable Row96 ...  Negative
96  Email me at testexamplecom Row97  br httpstest...   Neutral
97  pError 404 Page not foundp Row98  br httpstest...   Neutral
98  Special offer  httpsshopexamplecomdeals  Row99...  Positive
99  The movie was great awesome fun Row100  br htt...  Positive

[100 rows x 2 columns]